name: CarbonMessageDelete
version: '1.0-SNAPSHOT'
main: net.draycia.carbonMessageDelete.CarbonMessageDelete
api-version: '1.20'
dependencies:
  server:
    CarbonChat:
      load: BEFORE
      required: true
      join-classpath: true
